Add notifications to IRCops when they get restricted information.
DALnet/bahamut pull request #171
Opened 2020-07-03 16:12 UTC by jfcantu

Addresses issue #141.

Warn IRCops that normal users can't see what they're seeing, when they get:
- /whois reply with a user's unmasked hostname (`RPL_WHOISACTUALLY`)
- /whois reply indicating a user is squelched/warned (`RPL_WHOISTEXT`)
- /whois reply with a service tag that includes a umode restriction.
- +I/+e/+b lists for a channel if `XFLAG_HIDE_MODE_LISTS` is set.

2020-07-03 18:57 UTC, jfcantu commented
(FYI - the XFLAG part of this needs testing by someone with DALnet services.)

2020-07-22 18:10 UTC, kobishmueli commented on src/s_user.c
> +                        sendto_one(sptr, ":%s %d %s %s :%s [IRCop Restricted Information]", me.name, servicestag->raw, parv[0], name, servicestag->tag);
This is problematic and conflicts with our current SVSTAG usage.

Kobi.

2020-07-22 21:06 UTC, rscs commented
Per discussion in #operators, please hold on this one for now.  Thank you for jumping on it and the initiative -- we just need to all discuss how to consistently handle this across services replies and ircd replies.

There are some admin-only responses to consider (which would be marked admin-only instead of oper-only), which may include SVSTAGS.  So let's keep this open to discuss as a low-priority item.

2020-09-11 18:25 UTC, rscs requested changes
This needs more discussion per my note on July 22.

2026-03-17 14:40 UTC, closed without merging